theme = "monokai_pro"

[editor]
line-number = "relative"
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-encoding"] 
center = ["version-control"]

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
